### ISSUE TITLE
Detect moving objects for own video

### ISSUE THREAD

**Issue by mashiro7916** [BGU-CS-VIL/DeepMCBM#7]
I want detect the moving objects in the video from a dashcam video,I think I can use DeepMCBM to got the backround and calculate MSE to mark the moving objects.
But I don't know how to train for my video.maybe I must to edit the args.py file,but which arguments need to edit?
If my frames file named 001,I think I must edit:
MCBM_CKPT = "001.ckpt"
SEQUENCE = "001"
but I don't know how to  deal with the argument STN_ckpt.

**Comment by guy-erez** [comment]
Hi, in order to train DeepMCBM on your own video sequence, create a directory conatining the input frames "input/<sequance name>/frames/" or use the "parent_dir" argument to change the input path. You can refer to the "tennis" dir as an example. Than you can run DeepMCBM.py --dir <your new input dir> --source_shape <height> <width> .  This will train a new model on your data and will generate prediction at the end. I do need to tell you that the homography used at the STN training relly on the assumption that the scene is somewhat far from the camera, so I am not sure how well it will perform on a video from vehicle dashboard cam.
